-- ################################################## 高亮配色 ##################################################
local nvim = vim
local elements = {}

-- ====================================== init_highlight: 设置为monokai配色 =====================================
elements.init_highlight = function()
    nvim.opt.background = 'dark'
    nvim.cmd('highlight clear')

    nvim.api.nvim_set_hl(0, 'Cursor', {ctermfg=235, ctermbg=231, fg='#262626', bg='#f8f8f0'})
    nvim.api.nvim_set_hl(0, 'Visual', {ctermfg='NONE', ctermbg=59, fg='NONE', bg='#49483e'})
    nvim.api.nvim_set_hl(0, 'CursorColumn', {ctermfg='NONE', ctermbg=237, fg='NONE', bg='#262626'})
    nvim.api.nvim_set_hl(0, 'ColorColumn', {ctermfg='NONE', ctermbg=237, fg='NONE', bg='#262626'})
    nvim.api.nvim_set_hl(0, 'LineNr', {ctermfg=102, ctermbg='NONE', fg='#90908a', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'MatchParen', {ctermfg=197, ctermbg='NONE', cterm={underline=true}, fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'StatusLine', {ctermfg=231, ctermbg=241, cterm={bold=true}, fg='#f8f8f2', bg='#64645e'})
    nvim.api.nvim_set_hl(0, 'StatusLineNC', {ctermfg=231, ctermbg=241, fg='#f8f8f2', bg='#64645e'})
    nvim.api.nvim_set_hl(0, 'Pmenu', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'PmenuSel', {ctermfg='NONE', ctermbg=59, fg='NONE', bg='#49483e'})
    nvim.api.nvim_set_hl(0, 'IncSearch', {cterm={reverse=true}, ctermfg=193, ctermbg=16, fg='#C4BE89', bg='#000000'})
    nvim.api.nvim_set_hl(0, 'Search', {ctermfg=231, ctermbg=24, fg='#f8f8f2', bg='#204a87'})
    nvim.api.nvim_set_hl(0, 'Directory', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'SignColumn', {ctermfg='NONE', ctermbg=237, fg='NONE', bg='#262626'})
    nvim.api.nvim_set_hl(0, 'Normal', {ctermfg=231, ctermbg=235, fg='#f8f8f2', bg='#262626'})
    nvim.api.nvim_set_hl(0, 'Boolean', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Character', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Comment', {ctermfg=242, ctermbg='NONE', fg='#75715e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Conditional', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Constant', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Define', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'ErrorMsg', {ctermfg=231, ctermbg=197, fg='#f8f8f0', bg='#f92672'})
    nvim.api.nvim_set_hl(0, 'WarningMsg', {ctermfg=231, ctermbg=197, fg='#f8f8f0', bg='#f92672'})
    nvim.api.nvim_set_hl(0, 'Float', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Function', {ctermfg=148, ctermbg='NONE', fg='#a6e22e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Identifier', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Keyword', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Label', {ctermfg=186, ctermbg='NONE', fg='#e6db74', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'NonText', {ctermfg=59, ctermbg=235, fg='#262626',  bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Number', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Operator', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'PreProc', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Special', {ctermfg=231, ctermbg='NONE', fg='#f8f8f2', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'SpecialComment', {ctermfg=242, ctermbg='NONE', fg='#75715e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'SpecialKey', {ctermfg=59, ctermbg=237, fg='#49483e', bg='#262626'})
    nvim.api.nvim_set_hl(0, 'Statement', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'StorageClass', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'String', {ctermfg=186, ctermbg='NONE', fg='#e6db74', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Tag', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Title', {ctermfg=231, ctermbg='NONE', cterm={bold=true}, fg='#f8f8f2', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Todo', {ctermfg=95, ctermbg='NONE', cterm={reverse=true, bold=true}, fg='#75715e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Type', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'Underlined', {ctermfg='NONE', ctermbg='NONE', cterm={underline=true}, fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyClass', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyFunction', {ctermfg=148, ctermbg='NONE', fg='#a6e22e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyInterpolationDelimiter', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubySymbol', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyConstant', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyStringDelimiter', {ctermfg=186, ctermbg='NONE', fg='#e6db74', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyBlockParameter', {ctermfg=208, ctermbg='NONE', fg='#fd971f', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyInstanceVariable', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyInclude', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyGlobalVariable', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyRegexp', {ctermfg=186, ctermbg='NONE', fg='#e6db74', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyRegexpDelimiter', {ctermfg=186, ctermbg='NONE', fg='#e6db74', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyEscape', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyControl', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyClassVariable', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyOperator', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyException', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyPseudoVariable', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyRailsUserClass', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyRailsARAssociationMethod', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyRailsARMethod', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyRailsRenderMethod', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'rubyRailsMethod', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'erubyDelimiter', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'erubyComment', {ctermfg=95, ctermbg='NONE', fg='#75715e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'erubyRailsMethod', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'htmlTag', {ctermfg=148, ctermbg='NONE', fg='#a6e22e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'htmlEndTag', {ctermfg=148, ctermbg='NONE', fg='#a6e22e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'htmlTagName', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'htmlArg', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'htmlSpecialChar', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'javaScriptFunction', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'javaScriptRailsFunction', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'javaScriptBraces', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'yamlKey', {ctermfg=197, ctermbg='NONE', fg='#f92672', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'yamlAnchor', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'yamlAlias', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'yamlDocumentHeader', {ctermfg=186, ctermbg='NONE', fg='#e6db74', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'cssURL', {ctermfg=208, ctermbg='NONE', fg='#fd971f', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'cssFunctionName', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'cssColor', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'cssPseudoClassId', {ctermfg=148, ctermbg='NONE', fg='#a6e22e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'cssClassName', {ctermfg=148, ctermbg='NONE', fg='#a6e22e', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'cssValueLength', {ctermfg=141, ctermbg='NONE', fg='#ae81ff', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'cssCommonAttr', {ctermfg=81, ctermbg='NONE', fg='#66d9ef', bg='NONE'})
    nvim.api.nvim_set_hl(0, 'cssBraces', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='NONE'})

    -- 光标所在行显示颜色,hi CursorLine ctermfg=0 可使NonText的标点符号在选中时显示内容
    nvim.api.nvim_set_hl(0, 'CursorLine', {ctermfg='NONE', ctermbg='NONE', fg='NONE', bg='#202020'})
    nvim.api.nvim_set_hl(0, 'CursorLineNR', {ctermfg='NONE', ctermbg='NONE', fg='#ffff00', bg='#202020'})
end

-- ================================================ 返回通用元素 ================================================
return elements
